---
title: "Emergency WASH Access for Refugees"
author:
  - name: "Whitney N Knopp"
    orcid: "0009-0008-3245-2059"
    email: "whkn2760@colorado.edu"
    affiliation:
      - name: "University of Colorado Boulder"
        department: "Department of Civil, Environmental and Architectural Engineering"
        city: "Boulder"
        state: "CO"
        country: "USA"
date: today
format: html
editor: visual
---


# Introduction

[Brief description of your project and dataset]

# Methods

```{r load_packages}
library(unhcrwash)
library(tidyverse)
```

## Reading the Data

```{r reading_data}

# there are 2 wasy to read in this data because it is also a packange in R

# read data with R package
unhcrWASH_raw <- unhcrwash

# read csv from the /data path
unhcrwash_raw <- read_csv(here::here("data/raw/unhcrwash.csv"))

```

## Data Exploration Approach

## Initial Data Tidying

# Results

[This will be the core of your analysis with specific requirements]

# Conclusions

## Summary of Findings

## Questions and Next Steps